### ISSUE TITLE
Potential Licensing Conflicts

### ISSUE THREAD

**Issue by malekinho8** [whitead/paper-qa#73]
I looked up the licenses for several of the libraries this code base depends on, and there appears to be some potential conflicts. I've listed them below for discussion:

1. `html2text`: GPL 3.0 - requires all publicly distributed derivative work retain the GPL 3.0 license
2. `paper-scraper`: GNU GPL v3.0 - requires all publicly distributed derivative work retain the GNU GPL v3.0 license

Regarding converting html to text form, the [gazpacho](https://github.com/maxhumber/gazpacho) repository may be a good alternative (MIT license). For the paper-scraper tool, I have not been able to find anything yet.

**Comment by MilesCranmer** [comment]
@malekinho8 this is not how licensing works. Having a dependency with a different license is not an issue, so long as that dependency is not found within the repository. https://opensource.stackexchange.com/a/12229

> When you use Dependencies (direct or transitive) and you are not actually including this code of dependencies into your distribution, but you are just referencing it (and the user of the software will have to download and install it), then you can consider the information about the dependencies as metadata related to your code. So in your own license.txt you do not have to (for example) include all of the attribution notices and license terms of these dependencies that you are not distributing.

**Comment by whitead** [comment]
GPLv3 is a special case - if included as a library, one interpretation is that it becomes "linked". For example,

1. https://opensource.stackexchange.com/a/7331
2. https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

I guess since it's not entirely clear, we can leave GPLv3 imports for now. I would prefer to remove them in the future though so will leave issue open

**Comment by MilesCranmer** [comment]
Those answers are in a different context:

> What I will deliver to my customers will either be a .pyc file or a .so file ("compiled") with Cython 

Linking is compiler terminology. When your Python library has a dependency, they are not “linked” the same way as if you were compiling a C library. 

In Python, unless you are developing a C backend and compiling a binary that you then distribute, nothing is actually packaged or linked on your side, so the license of external libraries doesn’t factor in.

For example, both `make` and `bash` are GPLv3. It doesn’t pose an issue for the many libraries that use or depend on them, because libraries don’t package and distribute those.

**Comment by whitead** [comment]
`make` and `bash` fall under this clause:

> The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities. However, it does not include the work's System Libraries, or general-purpose tools or generally available free programs which are used unmodified in performing those activities but which are not part of the work. For example, Corresponding Source includes interface definition files associated with source files for the work, and the source code for shared libraries and dynamically linked subprograms that the work is specifically designed to require, such as by intimate data communication or control flow between those subprograms and other parts of the work.

"linking" is not meant to be compiler linking, but specifically this clause, which I believe could be read to include python packages:

> c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.


I'm not saying it's cut and dry, but I believe having gplv3 dependencies that are integral to the library changes how people interpret the license of this package.

**Comment by MilesCranmer** [comment]
> or general-purpose tools or generally available free programs

TIL, thanks! I didn’t know a separate rule applied to them. Although interestingly that rule seems overly general and you could argue any open source library is generally available…


Regarding the other part, to me it still reads as “packaged” i.e. distributed by you. But it’s not, it’s just some lines of code that references a package name. This is why nobody actually worries about this in open source unless you are distributing a combined package as a binary. I, the end user, am still the one downloading and installing these dependencies, and I could just as easily replace the dependency with another package that has an identical API, and install locally.

**Comment by MilesCranmer** [comment]
(When I last worked in industry, we reviewed each dependency of a package and their corresponding open-source license. If a package was incompatible with the internal licensing guidelines of the company, we would just replace the dependency ourselves on the internal version. i.e., one should never expect that a package's license should cover its tree of third-party dependencies; it is really a job for the end user, because you are not packaging the dependencies in one)
